---
title: "Visualisation of Simulations"
author: "Leonard Hambrecht"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
# Load necessary library
library(here)
library(knitr)
library(ggplot2)
```
Load data
```{r include=TRUE}
inputFilePaths <- list.files(path = here("Output", "Simulation"), pattern = "^simulation.*\\.RData$", full.names = TRUE)
load(inputFilePaths[1])

```

## Display results

```{r}
total_abundance <- round(sim_heli@population.description@N)
# Define labels
labels <- c("H-SG", "Rnd", "Sys", "ZZ", "ZZC", "FW-Sys_2C", "FW-ZZ_2C", "FW-Sys_G", "FW-ZZ_G", "QC-Sys")
xlims <- c(total_abundance * 0.8, total_abundance * 1.2)
par(mfrow = c(2, 5))

# Plot each histogram and add the corresponding label
histogram.N.ests(sim_heli, xlim = xlims)
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[1], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)


histogram.N.ests(sim_sys, xlim = xlims)
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[2], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_rnd, xlim = xlims)
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[3], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_zig, xlim = xlims)
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[4], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_zagcom, xlim = xlims)
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[5], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_fixW_sys_2C, xlim = c(round(sum(sim_fixW_sys_2C@population.description@N)) * 0.9, round(sum(sim_fixW_sys_2C@population.description@N)) * 1.05))
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[6], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_fixW_zigzag_2C, xlim = c(round(sum(sim_fixW_zigzag_2C@population.description@N)) * 0.9, round(sum(sim_fixW_zigzag_2C@population.description@N)) * 1.05))
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[7], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_fixW_sys_G, xlim = c(round(sum(sim_fixW_sys_G@population.description@N)) * 0.9, round(sum(sim_fixW_sys_G@population.description@N)) * 1.05))
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[8], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_fixW_zigzag_G, xlim = c(round(sum(sim_fixW_zigzag_G@population.description@N)) * 0.9, round(sum(sim_fixW_zigzag_G@population.description@N)) * 1.05))
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[9], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

histogram.N.ests(sim_quad, xlim = c(round(sum(sim_quad@population.description@N)) * 0.7, round(sum(sim_quad@population.description@N)) * 1.05))
usr <- par("usr")
text(x = usr[2], y = usr[4], labels = labels[10], adj = c(3.0, 0.9), col = "black", cex = 1.2, font = 2)

par(mfrow = c(1, 1))
```


